#
# Define individual supplement paths
#

#  VFZMAT added for Version 2.8, 9/19/16

#VBRDF_PATH   = $(VSUP_PATH)/vbrdf
#VBRDF_PATH   = $(VSUP_PATH)/vbrdf_Larc_developments
VBRDF_PATH    = $(VSUP_PATH)/vbrdf_experimental
VBRDFLIN_PATH = $(VSUP_PATH)/vbrdf_lin
VSLEAVE_PATH  = $(VSUP_PATH)/vsleave
VFZMAT_PATH   = $(VSUP_PATH)/vfzmat_reeng
VACCESS_PATH  = $(VSUP_PATH)/vaccessories

#
# Include individual supplement makefiles
#

include $(VBRDF_PATH)/makefile.vbrdf
include $(VBRDFLIN_PATH)/makefile.linsup
include $(VSLEAVE_PATH)/makefile.vsleave
include $(VFZMAT_PATH)/makefile.vfzmat_reeng
include $(VACCESS_PATH)/makefile.vaccess
