#  5/5/22. R. Spurr.
#    --Makefile for testing the new experimental BRDF system


VBRDF_LINSUP_SOURCES = 


VBRDF_LINSUP_SOURCES +=   \
   $(VBRDFLIN_PATH)/vbrdf_lin_sup_inputs_def.f90 \
   $(VBRDFLIN_PATH)/vbrdf_lin_sup_outputs_def.f90\
   $(VBRDFLIN_PATH)/vbrdf_sup_kernels.f90 \
   $(VBRDFLIN_PATH)/vbrdf_lin_sup_kernels.f90 \
   $(VBRDFLIN_PATH)/vbrdf_sup_routines.f90	  \
   $(VBRDFLIN_PATH)/vbrdf_lin_sup_routines.f90	  \
   $(VBRDFLIN_PATH)/vbrdf_lin_sup_masters.f90	  \
   $(VBRDFLIN_PATH)/vbrdf_lin_sup_mod.f90	  

$(OBJ_PATH)/%.o : $(VBRDF_LINSUP_PATH)/%.f90
	$(FC) $(FFLAGS) $< -o $@

